# Generated by Django 4.2.6 on 2023-11-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
