# Generated by Django 5.0.6 on 2024-06-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_usuarios_edad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
