# Generated by Django 5.0.6 on 2024-06-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_prendasropa_fecha_prendasropa_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendasropa',
            name='Descripcion',
            field=models.TextField(default='Descripción predeterminada'),
        ),
        migrations.AlterField(
            model_name='prendasropa',
            name='Fecha',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='prendasropa',
            name='Marca',
            field=models.CharField(default='Marca predeterminada', max_length=200),
        ),
        migrations.AlterField(
            model_name='prendasropa',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prendasropa',
            name='Titulo',
            field=models.CharField(default='Título predeterminado', max_length=200),
        ),
        migrations.AlterField(
            model_name='prendasropa',
            name='Vendedor',
            field=models.CharField(default='Nombre de vendedor', max_length=200),
        ),
    ]
