# Generated by Django 4.2.7 on 2023-11-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito')], max_length=20)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('codigo_seguridad', models.CharField(max_length=3)),
            ],
        ),
    ]
